### ISSUE TITLE
App crash when open extension in setting

### ISSUE THREAD

**Issue by Mrunknow3** [MrBoomDeveloper/Awery#130]
### Steps to Reproduce

Open app
Setting
Contant
Extension
Aniyomi
Click extension
But crash

### Expected Outcome

Open extension

### Actual Outcome

Crash

### Awery Version

Alpha latest version

### Operating System Version

Android 13

### Device Information

Poco m4 pro 4g

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/mrboomdeveloper/awery/releases/latest)** version of Awery. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
Download alpha as stable don't have extension support 
Also make sure to check discord messages

**Comment by Mrunknow3** [comment]
It's 7 months old
