### ISSUE TITLE
Language selector button is the settings for Android < 13

### ISSUE THREAD

**Issue by MrBoomDeveloper** [MrBoomDeveloper/Awery#26]

**Comment by eotw95** [comment]
Nice to meet you.
Is this issue still open?

**Comment by MrBoomDeveloper** [comment]
> Nice to meet you.
> Is this issue still open?

Hello! Yes, unfortunately, this setting is there, but it is hidden, as it works with glitches. Can you fix it?

**Comment by eotw95** [comment]
Thank you for reply.
This is my first time doing an OSS issue, so I would like to start with a simple issue.
Could you tell me the easiest issue?

**Comment by MrBoomDeveloper** [comment]
> Thank you for reply.
> This is my first time doing an OSS issue, so I would like to start with a simple issue.
> Could you tell me the easiest issue?

I think the easiest thing is this one and this: https://github.com/MrBoomDeveloper/Awery/issues/43

**Comment by eotw95** [comment]
Thank you. 
I will try #26 #43.
if I have any question, Can I comment here?

**Comment by MrBoomDeveloper** [comment]
> Thank you. I will try #26 #43. if I have any question, Can I comment here?

Sure np

**Comment by eotw95** [comment]
Where is a language selector button located?
And could you explain glitches?

**Comment by itsmechinmoy** [comment]
> Where is a language selector button located? And could you explain glitches?

I think he still hadn't added it inside the app but you can long-click the app>app settings>language

**Comment by MrBoomDeveloper** [comment]
> Where is a language selector button located? And could you explain glitches?

In assets/settings.json
The action, that performs langauge selection is located in com.mrboomdev.awery.ui.activity.settings.SettingsActions

**Comment by MrBoomDeveloper** [comment]
The language sometimes changes, sometimes not.
